[tool.poetry]
name = "dnafiber"
version = "0.1.0"
description = ""
authors = ["ClementPla <clement.playout@polymtl.ca>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
lightning
monai
segmentation_models_pytorch


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
