training:
  learning_rate: 0.0001
  weight_decay: 0.0001

trainer:
  max_epochs: 1000
  precision: 16-mixed
  check_val_every_n_epoch: 100

model:
  # encoder_name: mit_b2
  arch: steered_cnn
  # encoder_weights: imagenet


data:
  shape: 1024
  batch_size: 48
  root_img: /home/clement/Documents/data/DNAFiber/
  crop_size: [512, 512]
  use_cache: False
  cache_option: duplicated_memory
  sato_filter: False
  num_workers: 16