training:
  learning_rate: 0.00005
  weight_decay: 0.000001

trainer:
  max_epochs: 1000
  precision: 32
  check_val_every_n_epoch: 25
  accelerator: gpu
  devices: [0, 1]
  accumulate_grad_batches: 2


model:
  encoder_name: timm-efficientnet-b0
  encoder_weights: imagenet
  arch: unet



data:
  shape: 1024
  batch_size: 16
  root_img: /home/clement/Documents/data/DNAFiber/
  crop_size: [512,512]
  use_cache: True
  cache_option: duplicated_memory
  sato_filter: False
  num_workers: 8